function changefeed(x){document.getElementById("stream").innerHTML='<div style="height:30px;width:30px;box-shadow:0px 0px 0px 2px #e5a422;position:relative;border-radius:100%;margin:auto;margin-top:60px;"> <div style="position:absolute;top:10px;left:5px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="first"></div> <div style="position:absolute;top:12px;left:12px;width:6px;height:6px;background-color:#e5a422;border-radius:100%;"></div> <div style="position:absolute;top:10px;left:15px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="last"></div> </div>';setTimeout('$("#stream").load("count.php?q='+x+'");','1');if(x=="points"){document.getElementById("newselect").style.borderBottom="0px";document.getElementById("innernew").style.color="#C8D6D4";document.getElementById("hotselect").style.borderBottom="0px";document.getElementById("innerhot").style.color="#C8D6D4";document.getElementById("topselect").style.borderBottom="2px solid #e5a422";document.getElementById("innertop").style.color="#e5a422";document.getElementById("toptohot").innerHTML="TOP";}
if(x=="time"){document.getElementById("newselect").style.borderBottom="2px solid #e5a422";document.getElementById("innernew").style.color="#e5a422";document.getElementById("hotselect").style.borderBottom="0px";document.getElementById("innerhot").style.color="#C8D6D4";document.getElementById("topselect").style.borderBottom="0px";document.getElementById("innertop").style.color="#C8D6D4";document.getElementById("toptohot").innerHTML="NEW";}
if(x=="views"){document.getElementById("newselect").style.borderBottom="0px";document.getElementById("innernew").style.color="#C8D6D4";document.getElementById("hotselect").style.borderBottom="2px solid #e5a422";document.getElementById("innerhot").style.color="#e5a422";document.getElementById("topselect").style.borderBottom="0px";document.getElementById("innertop").style.color="#C8D6D4";document.getElementById("toptohot").innerHTML="HOT";}}
function pagination(x){document.getElementById("stream").innerHTML='<div style="height:30px;width:30px;box-shadow:0px 0px 0px 2px #e5a422;position:relative;border-radius:100%;margin:auto;margin-top:60px;"> <div style="position:absolute;top:10px;left:5px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="first"></div> <div style="position:absolute;top:12px;left:12px;width:6px;height:6px;background-color:#e5a422;border-radius:100%;"></div> <div style="position:absolute;top:10px;left:15px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="last"></div> </div>';setTimeout('$("#stream").load("count.php?q=views&count='+x+'");','1');}
function changeplaylist(x){document.getElementById("stream").innerHTML='<div style="height:30px;width:30px;box-shadow:0px 0px 0px 2px #e5a422;position:relative;border-radius:100%;margin:auto;margin-top:60px;"> <div style="position:absolute;top:10px;left:5px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="first"></div> <div style="position:absolute;top:12px;left:12px;width:6px;height:6px;background-color:#e5a422;border-radius:100%;"></div> <div style="position:absolute;top:10px;left:15px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="last"></div> </div>';setTimeout('$("#stream").load("count2.php?q='+encodeURIComponent(x)+'");','1');}
function user(x){document.getElementById("stream").innerHTML='<div style="height:30px;width:30px;box-shadow:0px 0px 0px 2px #e5a422;position:relative;border-radius:100%;margin:auto;margin-top:60px;"> <div style="position:absolute;top:10px;left:5px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="first"></div> <div style="position:absolute;top:12px;left:12px;width:6px;height:6px;background-color:#e5a422;border-radius:100%;"></div> <div style="position:absolute;top:10px;left:15px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="last"></div> </div>';setTimeout('$("#stream").load("count3.php?q='+encodeURIComponent(x)+'");','1');}
function search(x){document.getElementById("stream").innerHTML='<div style="height:30px;width:30px;box-shadow:0px 0px 0px 2px #e5a422;position:relative;border-radius:100%;margin:auto;margin-top:60px;"> <div style="position:absolute;top:10px;left:5px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="first"></div> <div style="position:absolute;top:12px;left:12px;width:6px;height:6px;background-color:#e5a422;border-radius:100%;"></div> <div style="position:absolute;top:10px;left:15px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="last"></div> </div>';setTimeout('$("#stream").load("count4.php?q='+encodeURIComponent(x)+'");','1');}
function loadcomments(x){window.scrollTo(0,350);document.getElementById("stream").innerHTML='<div style="height:30px;width:30px;box-shadow:0px 0px 0px 2px #e5a422;position:relative;border-radius:100%;margin:auto;margin-top:60px;"> <div style="position:absolute;top:10px;left:5px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="first"></div> <div style="position:absolute;top:12px;left:12px;width:6px;height:6px;background-color:#e5a422;border-radius:100%;"></div> <div style="position:absolute;top:10px;left:15px;width:10px;height:10px;background-color:#e5a422;border-radius:100%;-transition:all 0.3s;transition:all 0.3s;-transition:all 0.3s;transition:all 0.3s;" id="last"></div> </div>';setTimeout('$("#stream").load("/comments/?q='+encodeURIComponent(x)+'");','1');}
function showcloudsettings(){if(document.getElementById("cloudsettings").style.opacity=="0"){document.getElementById("cloudsettings").style.display="block";setTimeout("document.getElementById(\"cloudsettings\").style.top=\"120px\";document.getElementById(\"cloudsettings\").style.opacity=\"1\";$(\"#cloudsettings\").load(\"latestmoniker.php\");","1");}else{document.getElementById("cloudsettings").style.top="90px";document.getElementById("cloudsettings").style.opacity="0";setTimeout("document.getElementById(\"cloudsettings\").style.display=\"none\";","300");}}
function message(a,b,c){document.getElementById("message").style.display="block";document.getElementById("messagecontents").innerHTML=""+a+"";document.getElementById("messageurl").href=""+b+"";document.getElementById("messagebutton").innerHTML=""+c+"";if(c==undefined){document.getElementById("messagebutton").style.display="none";}
else{document.getElementById("messagebutton").style.display="block";}}
setInterval('elem = document.getElementById("first"); if(typeof elem !== "undefined" && elem !== null) { if(document.getElementById("first").style.left=="15px"){document.getElementById("first").style.left="5px";document.getElementById("last").style.left="15px";} else{document.getElementById("first").style.left="15px";document.getElementById("last").style.left="5px";} }','300');firstcount=-60;secondcount=$(window).width()+100;thirdcount=0-($(window).width()+100);setInterval('firstcount=firstcount+1.5;secondcount=secondcount-1.5;thirdcount=thirdcount+1;if(firstcount > $(window).width()+100){ firstcount = -60; };if(secondcount < 0-($(window).width()+100)){ secondcount = 1366; };if(thirdcount > 1280){ thirdcount = -60; };document.getElementById("car2").style.left=""+firstcount+"px";document.getElementById("car3").style.left=""+secondcount+"px";document.getElementById("nsa").style.left=""+thirdcount+"px";','10');num=0;setInterval('if(num == 1){ document.getElementById("window1").style.backgroundColor="#FFFFFF"; num = 0; } else{ document.getElementById("window1").style.backgroundColor="#eff3f2"; num = 1; } ','870');setInterval('if(num == 1){ document.getElementById("window2").style.backgroundColor="#FFFFFF"; num = 0; } else{ document.getElementById("window2").style.backgroundColor="#eff3f2"; num = 1; } ','993');setInterval('if(num == 1){ document.getElementById("window3").style.backgroundColor="#FFFFFF"; num = 0; } else{ document.getElementById("window3").style.backgroundColor="#eff3f2"; num = 1; } ','542');setInterval('if(num == 1){ document.getElementById("window4").style.backgroundColor="#FFFFFF"; num = 0; } else{ document.getElementById("window4").style.backgroundColor="#eff3f2"; num = 1; } ','661');setInterval('if(num == 1){ document.getElementById("window5").style.backgroundColor="#FFFFFF"; num = 0; } else{ document.getElementById("window5").style.backgroundColor="#eff3f2"; num = 1; } ','603');setInterval('if(num == 1){ document.getElementById("window6").style.backgroundColor="#FFFFFF"; num = 0; } else{ document.getElementById("window6").style.backgroundColor="#eff3f2"; num = 1; } ','696');function post(x){document.getElementById("headline").value="";document.getElementById("subtitle").value="";document.getElementById("full").value="";document.getElementById("popover").style.display="block";document.getElementById("finaltag").innerHTML="#"+x+"";setTimeout('document.getElementById("popover").style.opacity="1";document.getElementById("popover").style.webkitTransform="scale(1)";document.getElementById("popover").style.transform="scale(1)";','10');}
blinkcount=0;setInterval('if(blinkcount < 11){ if(document.getElementById("blink").style.opacity=="0"){ document.getElementById("blink").style.opacity="1"; } else { document.getElementById("blink").style.opacity="0"; }; } blinkcount++;','1000');page=location.hash.slice(1);if(page=="TopPosts"){changefeed('points');}
else{if(page=="AllPlaylists"){$("#stream").load("moreplaylists.php");}
else{if(page=="NewPosts"){changefeed('time');}
else{if(page=="HotPosts"){changefeed('views');}
else{var hasNumber=/\d/;if(hasNumber.test(page)){loadcomments(""+page+"");}
else{if(page){changeplaylist(""+page+"");}
else{changefeed("views");}}}}}}
window.onpopstate=function(){page=location.hash.slice(1);if(page=="TopPosts"){changefeed('points');}
else{if(page=="AllPlaylists"){$("#stream").load("moreplaylists.php");}
else{if(page=="NewPosts"){changefeed('time');}
else{if(page=="HotPosts"){changefeed('views');}
else{var hasNumber=/\d/;if(hasNumber.test(page)){loadcomments(""+page+"");}
else{if(page){changeplaylist(""+page+"");}
else{changefeed("views");}}}}}}}
$(window).scroll(function(){document.getElementById("indicator").style.width=""+($(window).scrollTop()/Math.round($("#stream").height()))*100+"%";if($(window).scrollTop()>560){$(".sidebar").css("position","fixed");$(".sidebar").css("top","-242px");$(".sidebar").css("background-color","#FFFFFF");$(".sidebar").css("box-shadow","-15px 0px 15px -30px #C8D6D4");$(".sidebar").css("z-index","9");if($(window).scrollTop()+$(window).height()>$('#footer').offset().top){topremainer=$('#footer').offset().top-($(window).scrollTop()+$(window).height())-222;$(".sidebar").css("top",topremainer);}else{$(".sidebar").css("top","-222px");}}else{$(".sidebar").css("position","absolute");$(".sidebar").css("top","60px");$(".sidebar").css("background-color","transparent");$(".sidebar").css("box-shadow","0px 0px 0px 0px");$(".sidebar").css("z-index","1");}});
